### ISSUE TITLE
Chrome notifications

### ISSUE THREAD

**Issue by bookercodes** [pusher/react-slack-clone#14]
When I receive a message, it would be pretty slick if I got a Chrome notification.

**Comment by huwiRandomDev** [comment]
@lukejacksonn @bookercodes Hey guys this would be my first contribution to a project is it alright if I take this on?

**Comment by lukejacksonn** [comment]
Sure, give it a go!

**Comment by bookercodes** [comment]
@DevFlex Hell yeah 💯!

To be clear, I am imagining web _push notifications_:

![](https://blog.kissmetrics.com/wp-content/uploads/2015/11/push-notifications-desktop-mobile.png)
![](https://blog.kissmetrics.com/wp-content/uploads/2015/11/push-notification-animation.png)

There are definetely some things to think about,

* When you click the notification, naturally, it should take you to the new message. At the moment, it isn't possible to link to a specific conversation (for example, `/react-slack-clone/messages/123`) so I am not sure how this will work
* How can we show notifications even when the app is closed? (I expect a lot of this will fall into place with [Chrome push notifications and service workers](https://developers.google.com/web/fundamentals/push-notifications/))

I would recommend you outline your approach before getting started. That way, @lukejacksonn and I can give you feedback before you spend too much time on implementation

We're happy to help in any way :)

**Comment by DevFlex** [comment]
Yes I thought that is what you meant. I had to checkout the codebase first to kind of get a feel for it.

Well my first plan of attack is to use the hook `onNewMessage` to determine when a new message comes in and then notify the user using the `new Notification('title', options)` within a new action I will create `showNotification` to display it. 

On componentDidMount within the index.js file I will ask the user for permission to show them notifications in the first place. I am not sure about the linking as of yet, but I assume I will be making use of the readCursor from chatkit and roomID and the message id to present the user with the right message when they click on the notification.

**Comment by DevFlex** [comment]
So I have some work done on it actually, but there are still some things I need to fix, but how do I go about committing this initial work for review? I have created a branch called `feature-notifications`, but when I tried pushing it to the origin I got a permission error. What do I need to do to get access?

**Comment by lukejacksonn** [comment]
Added here #54 🎉
