### ISSUE TITLE
the demo auth has an issue

### ISSUE THREAD

**Issue by Brantron** [pusher/react-slack-clone#24]
I kept getting redirected to provide access to github with a message that an unusually high number of requests were being made

**Comment by lukejacksonn** [comment]
We don't store any tokens locally (yet/anymore) instead we just do the auth flow every page refresh, getting a new token from GitHub every time. So you might see this, message during development.

From my testings, this is annoying but you can just "reauthorise" and everything still works as expect.

Will try address token storage asap though. Thanks for the report 👍

**Comment by lukejacksonn** [comment]
Hey @Brantron I believe this is fixed with the latest deploy 🎉 Going to close here but please reopen or create a new issue if you find anything else amiss 🙇
