### ISSUE TITLE
Crash after attachement

### ISSUE THREAD

**Issue by EduardoSaverin** [pusher/react-slack-clone#25]
*Attachment(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.*

` 12 | componentDidMount() {`
`  13 |   this.props.link &&`
`  14 |     this.props.user`
`  15 |       .fetchAttachment({ url: this.props.link })`
`  16 |       .then(fetched =>`
 ` 17 |         this.setState({ src: fetched.link, name: fetched.file.name })`
 ` 18 |       )`

**Comment by lukejacksonn** [comment]
Did it actually crash, or just just print an error/warning?

**Comment by EduardoSaverin** [comment]
Crashing with error printed on screen.

**Comment by lukejacksonn** [comment]
Thanks, I will look into it.

**Comment by EduardoSaverin** [comment]
I fixed it.

**Comment by lukejacksonn** [comment]
Fixed by #51 🎉
