### ISSUE TITLE
Archive Channel Feature

### ISSUE THREAD

**Issue by ichtrojan** [pusher/react-slack-clone#42]

**Comment by lukejacksonn** [comment]
Hey 👋 I haven't had much time to go through these issues since release. Just going through now. Did you know you can do `/leave` to leave a channel. Once all members have left the roomthen it is essentially archived. Is this what you meant?

**Comment by ichtrojan** [comment]
A channel should be archived but messages can be viewed but no messages can be sent to such channel

**Comment by lukejacksonn** [comment]
Thanks for the feedback! Chatkit doesn't currently support this feature so there is not much we can do on the frontend to achieve this.. yet. But we are logging all these requests and working on them in priority order. So perhaps soon.
