### ISSUE TITLE
New rooms missing when logged in from two separate accounts

### ISSUE THREAD

**Issue by teminer** [pusher/react-slack-clone#43]
rajaraodv --> from #chatkit public beta slack:

> I tried to use the "slack clone" app, I logged in using two different github accounts on two different browsers, but I'm unable to communicate b/w the two users. I dont see any rooms that user1 created in the other instance

> How to debug this?"

**Comment by lukejacksonn** [comment]
One of the users have to invite the other to a common room using `/invite <username>`
