### ISSUE TITLE
Wht `browserslist` in package.json?

### ISSUE THREAD

**Issue by ghost** [pusher/react-slack-clone#57]
Is it possible to use `browserslist` in package.json with `react-scripts`? But just on `next` version, right?

**Comment by lukejacksonn** [comment]
Hey 👋 I am not sure what you mean by this! I have never used `browserslist` in a package.json.. what does it do?

**Comment by lukejacksonn** [comment]
I am going to close this here, feel free to re-open if you still have questions/issues!
