### ISSUE TITLE
Attachment token expired

### ISSUE THREAD

**Issue by alexey13** [pusher/react-slack-clone#63]
Hi Luke. Let you know that attachment links live very short period. Try to attach pdf for example and click after a minute on the link to download
`<Code>AccessDenied</Code>`
`<Message>Request has expired</Message>`
`<X-Amz-Expires>60</X-Amz-Expires>`

**Comment by alexey13** [comment]
What solution to use, how you think? Fetch links every 59 seconds? With fetch by click have problems.

**Comment by lukejacksonn** [comment]
Hey @alexey13 thanks again for the report.. how about this?

**Comment by alexey13** [comment]
Yep, like it, refetch by period

**Comment by lukejacksonn** [comment]
Alright! That is merged now 👍
